version: '2'

services:
  app:
    build: ./docker
    hostname: app
    cap_add:
      - ALL
    links:
      - database:database-host
    volumes:
        # 1 - Persist database outside container.
        # 2 - Use ssh config from host.
        # 3 - Use git config from host.
        # 4 - Place app files.
      - $HOME/.databases/drupal-boilerplate:/var/lib/mysql
      - $HOME/.ssh:/taller/.ssh
      - $HOME/.gitconfig:/taller/.gitconfig
      - $PWD:/drupal/app

  database:
    image: mysql:5.6
    container_name: 'drupal-boilerplate-database'
    environment:
      - MYSQL_USER=drupal
      - MYSQL_DATABASE=drupal
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
